apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-deprecated-apis
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-v1-22-removals
    match:
      any:
      - resources:
          kinds:
          - admissionregistration.k8s.io/*/ValidatingWebhookConfiguration
          - admissionregistration.k8s.io/*/MutatingWebhookConfiguration
          - apiextensions.k8s.io/*/CustomResourceDefinition
          - apiregistration.k8s.io/*/APIService
          - authentication.k8s.io/*/TokenReview
          - authorization.k8s.io/*/SubjectAccessReview
          - authorization.k8s.io/*/LocalSubjectAccessReview
          - authorization.k8s.io/*/SelfSubjectAccessReview
          - certificates.k8s.io/*/CertificateSigningRequest
          # - coordination.k8s.io/*/Lease
          - extensions/*/Ingress
          - networking.k8s.io/*/Ingress
          - networking.k8s.io/*/IngressClass
          - rbac.authorization.k8s.io/*/ClusterRole
          - rbac.authorization.k8s.io/*/ClusterRoleBinding
          - rbac.authorization.k8s.io/*/Role
          - rbac.authorization.k8s.io/*/RoleBinding
          - scheduling.k8s.io/*/PriorityClass
          - storage.k8s.io/*/CSIDriver
          - storage.k8s.io/*/CSINode
          - storage.k8s.io/*/StorageClass
          - storage.k8s.io/*/VolumeAttachment
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: NotEquals
        value: DELETE
      - key: "{{request.object.apiVersion}}"
        operator: AnyIn
        value:
        - admissionregistration.k8s.io/v1beta1
        - apiextensions.k8s.io/v1beta1
        - apiregistration.k8s.io/v1beta1
        - authentication.k8s.io/v1beta1
        - authorization.k8s.io/v1beta1
        - certificates.k8s.io/v1beta1
        - coordination.k8s.io/v1beta1
        - extensions/v1beta1
        - networking.k8s.io/v1beta1
        - rbac.authorization.k8s.io/v1beta1
        - scheduling.k8s.io/v1beta1
        - storage.k8s.io/v1beta1
    validate:
      message: >-
        {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.22.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {}
  - name: validate-v1-25-removals
    match:
      any:
      - resources:
          # NOTE: PodSecurityPolicy is completely removed in 1.25.
          kinds:
          - batch/*/CronJob
          - discovery.k8s.io/*/EndpointSlice
          - events.k8s.io/*/Event
          - policy/*/PodDisruptionBudget
          - policy/*/PodSecurityPolicy
          - node.k8s.io/*/RuntimeClass
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: NotEquals
        value: DELETE
      - key: "{{request.object.apiVersion}}"
        operator: AnyIn
        value:
        - batch/v1beta1
        - discovery.k8s.io/v1beta1
        - events.k8s.io/v1beta1
        - policy/v1beta1
        - node.k8s.io/v1beta1
    validate:
      message: >-
        {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.25.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {}
  - name: validate-v1-26-removals
    match:
      any:
      - resources:
          kinds:
          - flowcontrol.apiserver.k8s.io/*/FlowSchema
          - flowcontrol.apiserver.k8s.io/*/PriorityLevelConfiguration
          - autoscaling/*/HorizontalPodAutoscaler
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: NotEquals
        value: DELETE
      - key: "{{request.object.apiVersion}}"
        operator: AnyIn
        value:
        - flowcontrol.apiserver.k8s.io/v1beta1
        - autoscaling/v2beta2
    validate:
      message: >-
        {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.26.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {}
  - name: validate-v1-27-removals
    match:
      any:
      - resources:
          kinds:
          - storage.k8s.io/*/CSIStorageCapacity
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: NotEquals
        value: DELETE
      - key: "{{request.object.apiVersion}}"
        operator: AnyIn
        value:
        - storage.k8s.io/v1beta1
    validate:
      message: >-
        {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.27.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {}
